## 13. 예외 처리

> 자주 사용하는 부분
>
> - 파일 처리 (open (), close() )
> - 네트워크
> - DB  -> open, close, commit.... 

### Exception

> try : 실행할 명령
>
> except 예외 as 변수 :
>
> ​	오류 처리문
>
> else : 
>
> ​	예외가 발생하지 않을 때의 처리

- nameError : 명칭이 발견되지 않는다. 
- ValueError : 값이 잘못됬다. 
- ZeroDivisionError : 0으로 나눔
- indexError : 첨자가 범위를 벗어났다.
- TypeError : 타입이 안맞다



### raise 명령

> 고의로 예외 발생시킴(조건문과 결합하여?)

```python
def calcsum(n):
    if (n < 0):
        raise ValueError
    sum = 0
    for i in range(n+1):
        sum = sum + i
    return sum

try:
    print("~10 =", calcsum(10))
    print("~-5 =", calcsum(-5))
except ValueError:
    print("입력값이 잘못되었습니다.")
```



### 자원정리

### finally 블록

```python
try:
    print("네트워크 접속")
    a = 2 / 0
    print("네트워크 통신 수행")
finally:
    print("접속 해제")
print("작업 완료")
```



### assert 문장 

- 프로그램의 현재 상태가 맞는지 확인

![image-20210112163611458](C:\Users\hansoo\AppData\Roaming\Typora\typora-user-images\image-20210112163611458.png)